### ISSUE TITLE
java.lang.NoClassDefFoundError after Redex(ing)

### ISSUE THREAD

**Issue by codeskraps** [facebook/redex#129]
Logcat output attached

[logcat_redex.txt](https://github.com/facebook/redex/files/250724/logcat_redex.txt)

**Comment by satnam6502** [comment]
Hello @codeskraps , I'd like to help you out here. Shortly I am going to add a section to our documentation to explain how to retain classes and fields and methods that would otherwise get stripped out by ProGuard or Redex. I see that the class that is not found here is called `com.crashlytics.android.core.internal.CrashEventDataProvider` so guessing from its name perhaps this is a class that is accessed by reflection?

Can you provide me with a little more context? The source code on GitHub? A link to the APK?

Thank you kindly.

**Comment by codeskraps** [comment]
We are using [Crashlytics](http://try.crashlytics.com/) in our project as a crash reporting tool. Unfortunately their code is not open source. Attached is the redex apk output with the issue


[output.zip](https://github.com/facebook/redex/files/254972/output.zip)

**Comment by wisechengyi** [comment]
having similar issue with crashlytics and redex, wonder if there is any progress on this front.
```
02-28 14:15:26.932  3754  3754 E AndroidRuntime: FATAL EXCEPTION: main
02-28 14:15:26.932  3754  3754 E AndroidRuntime: Process: com.twitter.android.beta, PID: 3754
02-28 14:15:26.932  3754  3754 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lq;
02-28 14:15:26.932  3754  3754 E AndroidRuntime: 	at java.lang.Class.getDeclaredAnnotation(Native Method)
02-28 14:15:26.932  3754  3754 E AndroidRuntime: 	at java.lang.Class.getAnnotation(Class.java:2352)
02-28 14:15:26.932  3754  3754 E AndroidRuntime: 	at io.fabric.sdk.android.h.<init>(ｹｲﾀｲ:46)
02-28 14:15:26.932  3754  3754 E AndroidRuntime: 	at com.crashlytics.android.core.h.<init>(ﾟ:189)
02-28 14:15:26.932  3754  3754 E AndroidRuntime: 	at com.crashlytics.android.core.h.<init>(ﾟ:180)
02-28 14:15:26.932  3754  3754 E AndroidRuntime: 	at com.crashlytics.android.core.h$a.a(ﾟ:166)
02-28 14:15:26.932  3754  3754 E AndroidRuntime: 	at f$a.a(ﾟ:137)
```

**Comment by wisechengyi** [comment]
ah my bad. will follow #134
