### ISSUE TITLE
LocalDcePass is incorrectly marked as DoesNotSync

### ISSUE THREAD

**Issue by arnaudvenet** [facebook/redex#157]
The test 'test/integ/PropagationTest.cpp' was failing in a baffling way on my install: although the Peephole pass would correctly insert the const-string opcode, the LocalDce pass would see a completely different opcode at that point (a floating-point multiplication). Since LocalDce is marked with the DoesNotSync tag, it doesn't sync the pending MethodTransform's produced by Peephole, which caused the discrepancy. When removing the tag, the test passes successfully.

I would suggest making all passes do a sync_all() by default, which would prevent this kind of hard-to-diagnose problem. In my experiments with Redex, performance was not an issue and I think it would be safer to do so.

**Comment by bertmaher** [comment]
Thanks for pointing this out -- there was actually a bug introduced in LocalDce that was causing this problem.  I've reworked the transform/sync process so you get a clean assert if you try to inspect a method's instruction vector while transforming it.  I'd prefer not to force syncing between passes, since the slowdown is pretty noticeable on large apps (*cough* Facebook *cough*).

**Comment by arnaudvenet** [comment]
Sounds reasonable. Thanks for the fix!
