### ISSUE TITLE
Why the software history was not kept?

### ISSUE THREAD

**Issue by gustavopinto** [facebook/redex#164]
Hi there,

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. However, I observed that some projects, like _redex_, deleted their software history.

https://github.com/facebook/redex/commit/49f9e3446d7c68b4a29f16fd14fc334bd4bb4b86

Knowing that software history is indispensable for developers (e.g., developers need to refer to history several times a day), I would like to ask redex developers the following four brief questions:

1. Why did you decide to not keep the software history?
2. Do the core developers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
3. Do the newcomers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by bertmaher** [comment]
We have the full history in Facebook's internal repository, but our tool for exporting a new project to github uses the current internal repo state as the initial commit.  Since then we maintain full history in our public repo.  So, the only developers who would be harmed by the lack of (comparatively ancient) history, are external developers seeking to modify more stable parts of the codebase.  I can't speak to their experience, unfortunately.

**Comment by gustavopinto** [comment]
Hi @bertmaher, 

thanks once again for answering our research inquiries. We were able to collect 35 responses and we drafted a research paper with the results. The paper was submitted and accepted for the 14th International Conference on Open Source Systems (http://oss2018.org/). You can find the paper [here](http://gustavopinto.org/lost+found/oss2018.pdf). Hope you enjoy reading the paper!

Thanks again,

Gustavo
