### ISSUE TITLE
Unqualified uses of 'string' in 'ProguardLexer.cpp'

### ISSUE THREAD

**Issue by arnaudvenet** [facebook/redex#165]
I'm sorry to bring this up again, but would it be possible to also qualify all occurrences of 'string' in 'ProguardLexer.cpp'? The commit 2516b12 only fixes ProguardLexer.h and that still causes compilation issues in my environment. Thanks.

**Comment by dcolascione** [comment]
Why is it causing issues in your environment? Redex's compilation units 
should be distinct from your own, the ones with the custom string type, 
and since the mangled names *already* distinguish between std::string 
and your::string, without fully qualifying the name in the source, the 
linker shouldn't care either.

**Comment by arnaudvenet** [comment]
In our corporate development environment, the unqualified 'string' type defaults to our internal implementation. Since Redex also uses 'std::string', our compiler cannot disambiguate an unqualified reference to the 'string' type.

**Comment by dcolascione** [comment]
Then you are not using a C++ compiler. Why do you expect anything external and conforming to C++ to work?

**Comment by bertmaher** [comment]
I don't really mind changing this since it's consistent with the rest of our codebase anyways, but I struggle to understand what kind of environment would do this.

**Comment by dcolascione** [comment]
Sure, but who knows what other weird things this non conforming compiler might do? Do you really want to support that environment?

**Comment by arnaudvenet** [comment]
Awesome! Thanks for the fix.
