### ISSUE TITLE
Add Usage instructions for Buck

### ISSUE THREAD

**Issue by kageiit** [facebook/redex#179]
We use both Gradle and buck for our builds. It would be nice to know how FB uses redex in their buck files to operate efficiently and take advantage of the caching mechanisms etc in buck.

Is it mostly just a genrule? How is it structured? Some usage details would be great.

**Comment by bertmaher** [comment]
Sure!  Our overall build setup is complicated but the basic process of plugging in redex is more or less straightforward, using an `apk_genrule`.   Anyways, let's say you have an `android_binary` set up:
```
  android_library(
    name = 'test',
    srcs = java_files,
    deps = test_deps,
  )
  android_binary(
    name = 'test_pre',
    manifest = 'AndroidManifest.xml',
    keystore = '//keystores:prod',
    package_type = 'release',
    deps = [':test'],
  )
```
Then you can apply redex to the `test_pre` target.  We build redex in-tree, so we refer to the binary using buck's `$(location ...)` syntax.  It's even easier if you have redex installed on the system, since you can just call it directly.
```
  apk_genrule(
    name = 'test_redex',
    apk = ':test_pre',
    cmd = '$(location //redex) -o $OUT $APK',
    out = name + '_redex.apk',
  )
```
