### ISSUE TITLE
Why does get_children return vector<const DexClass*> instead of vector<DexClass*>?

### ISSUE THREAD

**Issue by kamalmarhubi** [facebook/redex#205]
I can't see any reason for this: I can get a pointer to the same object without casting away constness like so:

```c++
// some_class is const DexType*
auto some_class = get_children(DexType::get_type("Ljava/lang/Object;"))[0]; 
// mutable_same_class is an identical pointer but without const
auto mutable_same_class = DexType::get_type(some_class->get_name());
```

Indeed I do this to keep well clear of things that look like undefined behavior.

A similar question: why does `DexMethod::get_method` require non-const pointers? I haven't studied the code carefully, but my understanding is that it should only be returning me a pointer to an object that already exists. This shouldn't result in any modification to the passed in `DexType`, `DexString`, or`DexProto`.

**Comment by minjang** [comment]
Thanks for your opinions.

1) As you pointed out, `some_class` has `const`. As of now, `DexType::get_type` returns a non-const `DexType*`. However, `DexType::get_type` takes a `DexString`. The constness of `some_class` needs not to be propagated to its property. Due to our uniqueness, the resulting two `DexType*` are the same pointers, but different constness. It is okay. This is simply because `Dex::get_type` returns a non-const object.

2) We may need to update the `DexCode` member field of `DexMethod`.

In general, `const` in C++ is very tricky. Thanks for bring up this `const` issues. We may improve the consistency in the future.
