### ISSUE TITLE
version scheme change?

### ISSUE THREAD

**Issue by ilovezfs** [facebook/redex#274]
The last version was semver 1.1.0. The latest version is non-semver 2017.10.31. Is this an intentional shift or was the tag misnamed?

**Comment by justinjhendrick** [comment]
This was intentional. We're planning on moving to a semi-continuous release schedule (from the stable branch).

We plan to have TravisCI create a release for every commit to redex-stable, it would be hard to maintain semantic versioning in this new scheme. That's why we chose a date based version number instead.

**Comment by ilovezfs** [comment]
OK, thanks!
