### ISSUE TITLE
RenameClassesV2 pass fails on non-binary xmls

### ISSUE THREAD

**Issue by mvolkus** [facebook/redex#300]
During resource renaming in `rename_classes_in_layouts` method, `get_xml_files` returns all xml files in res folder, which may include not only Android binary xml, but also standard xml files or empty files.

Trying to parse these xml, the xml parser fails with error:
`LOG_FATAL_IF(dtohl(chunk->size) != len, "Can't read header size");` 
, or if the file is empty, `mmap` fails.

**Comment by wsanville** [comment]
Hi, can you share some details on what is the valid use case for having non-binary XML files in the res directory? I could have a misunderstanding here, but was under the impression that the stock Android build tools would convert all of them to a binary format.

**Comment by mvolkus** [comment]
User can place raw xml files in res/raw folder, which will not be converted into binary xml. It may be necessary if the app uses it's own xml parser.

**Comment by justinjhendrick** [comment]
Why are there text xml or empty xml files in your apk? How did you create this apk? I'm pretty sure `aapt` and `aapt2` compile all xml files in the res directory.

The author of [this blog](http://www.atcomm.com.au/Atcomm-Underground/Java/Compiled-and-Noncompiled-Android-Resources.html) claims that text xml files should be in `res/raw`. What happens if you move your empty/text xmls into that directory?

**Comment by wsanville** [comment]
Okay, thanks for the info. Sounds like we should not attempt to read files in a res/raw directory in `rename_classes_in_layouts` since they could be in an arbitrary/unknown format.

If any class names do appear in a res/raw XML file, then I'd suggest configuring RenameClassesV2 to avoid renaming the class.
