### ISSUE TITLE
Testing instructions in README are out of date

### ISSUE THREAD

**Issue by JoeLoser** [facebook/redex#310]
When I follow the instructions in the top-level `README.md`, they do not work as intended.

Namely, when I invoke `test/setup.sh`, it downloads GTest 1.7 as expected (any reason not to use 1.8?). However, there is no `Makefile` in the `test` directory for me to run `make check` against. Am I expected use Autotools/configure the `Makefile.am` to generate a regular `Makefile`?

**Comment by justinjhendrick** [comment]
Yeah, sorry. The OSS tests are in a sad state of disrepair. We use a different build system (buck) internally to run them, so it's hard to remember keep the OSS build system working. Let me see if we can clean those up for you.

**Comment by justinjhendrick** [comment]
Okay, so I'm trying to run the tests via this github repo now.

I was able to invoke `make check`. I think it's because I built redex itself first. The automake file at the root of the repo will generate the `Makefile` for the test directory. (`autoreconf -ivf && ./configure && make -j4`) from the root of the repo.

But I ran into a compilation error after that. Investigating now.

**Comment by justinjhendrick** [comment]
But we should probably mention the automake step in the test section

**Comment by vsamtuc** [comment]
Is there any chance that the build scripts will be updated? It would be quite useful for those of us wanting to play with the code. Thanks!

**Comment by justinjhendrick** [comment]
I spent a few hours today trying to fix this. The issue is that `redex/Makefile.am` is kept up to date, but the `redex/test/.../Makefile.am` files are not. To fix this issue (instead of band-aiding until another file is created), I want to export variables from `redex/Makefile.am` to the `redex/test/.../Makefile.am` files but I'm struggling to do so. I'm not sure why, but exporting variables in `redex/Makefile.am` moves their definition to the bottom of the generated `Makefile`, it seems. So, the values we need to build `libredex` and `redex-all` aren't available when they're asked for :(

I honestly don't know much about automake and I'm finding it rather difficult to use. I wonder if it's time to just convert it all to cmake. I've heard that's much better.

**Comment by JoeLoser** [comment]
I'm not too familiar with Autotools besides the basics, so I can't be much help likely.

I'd be in favor of the project migrating to CMake. I wouldn't be surprised if Facebook's OSS projects are all moving in that direction. I believe Folly is about to deprecate support for Autotools too.

**Comment by justinjhendrick** [comment]
@vsamtuc, some help would definitely be appreciated! I've created a pull request with my work from Friday: #342

**Comment by agampe** [comment]
The `Makefile`s and docs are updated. `gtest`/`gmock` do not need to be downloaded explicitly anymore. Just run `make check` at the top-level.
