### ISSUE TITLE
Question: what are cases where more than one DexStore could exist?

### ISSUE THREAD

**Issue by kamalmarhubi** [facebook/redex#400]
I'm trying to understand the top level structure of redex. In particular, there's a notion of a DexStore, which is not very well documented. The closest I've come to documentation is in `redex.py` and `redex-all/main.cpp`:
- any file that is a .dex file is considered part of the classes store, which is the main store
- other files have some metadata written out by `redex.py` in JSON format, which `redex-all` inspects
- the metadata appears to be based on data in `assets/*/metadata.txt` and includes info about dependencies (?)

On a hunch, I figured this is maybe a Buck internal detail. Indeed, I found code there that appears to generate these metadata files: [PreDexMerge](https://github.com/facebook/buck/blob/7eadfaba6254110230b37f67c4338f49919b9e77/src/com/facebook/buck/android/PreDexMerge.java#L421-L431)

Are non-`classes` DexStores a Buck-only case?

**Comment by andreasnomikos** [comment]
No its a general case related to feature splits.
see
https://developer.android.com/studio/projects/dynamic-delivery

Every classes.dex that belongs to a different split is assigned to a different store.

Feature splits impose constraints to the optimizer because there are some optimizations that are not allowed to be performed across DexStores. e.g. you would not be able to inline a method call from a secondary DexStore into the primary DexStore.

**Comment by kamalmarhubi** [comment]
Hm, I assumed it couldn't be related to that because the DexStore feature is in the original release back in 2016, but dynamic delivery is only from the last year. And even Instant Apps are newer than the original Redex. Additionally, the manifest info mentioned in that page isn't the same as what redex.py appears to parse.

**Comment by andreasnomikos** [comment]
Facebook had an in-house implementation of dynamic delivery before google rolled its own with play services. The spec for the definition of those was completely independent from google and gradle.

**Comment by int3** [comment]
Thanks @andreasnomikos for answering the question!
