### ISSUE TITLE
Comparison to proguard is missing from readme or blog post.

### ISSUE THREAD

**Issue by runningcode** [facebook/redex#48]
To me, the Readme is incomplete without a comparison to Proguard.
I would like to see performance differences between this tool and Proguard as well as why it was built. This would me in deciding whether or not to use this library

**Comment by bertmaher** [comment]
The short answer to this is that our observed size/speed wins on the Facebook app come on top of ProGuard -- we use both.  I don't consider it an either/or proposition, which is why I haven't compared the two.  But I've seen this question a lot so it's probably worth adding it as a FAQ to the README.

**Comment by bertmaher** [comment]
README has been updated, thanks for the suggestion.
