### ISSUE TITLE
Can Interdex optimize the speed of apk's cold boot on Android 9.0?

### ISSUE THREAD

**Issue by zhangkevd** [facebook/redex#483]
system：Ubuntu20.04
branch:stable

config：
`
{
  "redex": {
    "passes": [
      "InterDexPass"
    ]
  },
  "InterDexPass": {
    "static_prune": false,
    "emit_canaries": true,
    "minimize_cross_dex_refs": true
  },
  "stats_output": "redex-stats.txt",
  "coldstart_classes": "list_of_classes.txt"
}
`
hprof get from Simulator android4.4

But after tests on devices 9.0, i found that there is no obvious acceleration effect, the original start at 700~800ms, optimization results are not significantly different.

Did I do something wrong?

**Comment by benjaminRomano** [comment]
From my experience, I've seen the biggest impact from Interdex on older devices running older OS versions and saw minimal impact on mid-tier devices and almost no impact on high-tier flagship devices. I'm not sure how much the OS version contributes to those results compared to hardware specs. For some context, in my situation I am loading approximately 15k classes on cold start.

**Comment by zhangkevd** [comment]
> From my experience, I've seen the biggest impact from Interdex on older devices running older OS versions and saw minimal impact on mid-tier devices and almost no impact on high-tier flagship devices. I'm not sure how much the OS version contributes to those results compared to hardware specs. For some context, in my situation I am loading approximately 15k classes on cold start.

On your suggestion, I tested a 4.4 device again, ,it's a pad,and there was no significant optimization.

**Comment by wsanville** [comment]
Hello, we're not really in a position to help you debug this, since it'll be up to you to understand and profile your application to determine how much IO is happening on startup and what exactly is on the critical path for startup.

Other things that might be relevant:
- Double check your list_of_classes.txt makes sense.
- ART on modern OS versions could already be helping out your startup performance by generating an .art file (app image): https://source.android.com/devices/tech/dalvik/configure#how_art_works
