### ISSUE TITLE
Class failed lock verification and will run slower

### ISSUE THREAD

**Issue by benjaminRomano** [facebook/redex#528]
**Background**
Using latest R8 stable and the following config:
```
{
 "redex": {
   "passes": [
     "AccessMarkingPass",
     "ReBindRefsPass",
     "InterDexPass",
     "RegAllocPass",
     "MakePublicPass",
      # Above passes were needed to avoid Redex build failures
      # DedupBlocksPass is the relevant optimization 
     "DedupBlocksPass"
   ]
 },
 "InterDexPass": {
        "type_refs_limit": 32700
 },
 "RegAllocPass": {
   "live_range_splitting": false
 },
 "debug_info_kind": "no_custom_symbolication",
 "string_sort_mode": "class_order",
 "bytecode_sort_mode": "class_order",
 "ir_type_checker": {
   "run_after_each_pass": false,
   "check_no_overwrite_this": false,
   "verify_moves": false
 }
}
```

I am seeing the following error message:
```
Class Gc failed lock verification and will run slower.
    Common causes for lock verification issues are non-optimized dex code
    and incorrect proguard optimizations.
```

This leads to runtime verification of the `Gc` class which is problematic as it occurs early in our startup flow and takes 200-300ms depending on the device.

The before/after bytecode can be found here: https://gist.github.com/benjaminRomano/3d81cc855f54916ba1ec160863a25332

This issue was also encountered when trying with latest master.

cc @danzimm

**Comment by agampe** [comment]
Non-stable has updated passes that try to avoid some of these issues. `CopyPropagation` now attempts to allocate a dedicated register for a clique of registers of the same lock. `RemoveRecursiveLocks` will attempt to remove recursive locks that happen when inlining synchronized methods on self.

All other passes do not care much. Minimal configs are *not* assumed or guaranteed to give you optimal performance.

In general, your code snippet is **way** too large to investigate. You'll have to find a small reproducer, or investigate yourself. On a `userdebug` build of Android 10 (e.g., the emulator), you can make the verifier spew more data (both during `dex2oat` and at runtime). Something like
```
adb shell setprop dalvik.vm.extra-opts "'-verbose:verifier,verifier-debug'" # Runtime
adb shell setprop dalvik.vm.dex2oat-flags "'--runtime-arg -verbose:verifier,verifier-debug'" # Compile time (install/AoT)
```
(You may not need the `-debug` version to pinpoint where the supposed lock issue is detected.)

**Comment by benjaminRomano** [comment]
Thanks for the pointers @agampe! 

This minimal config is the smallest config file that reproduced the lock verification issue. This was solely to root cause what the offending pass was. We don't intend to use this in practice.

I enabled verifier logs and used the following command to force AOT compilation:
```
pm compile -m speed <package_name>
```
I filtered the logs with the following command (I found the error messages to grep for from [here](https://android.googlesource.com/platform/art/+/refs/heads/master/runtime/verifier/register_line.cc])):
```
cat logs.txt | grep -e "mismatched lock levels for register" -e "monitor-enter stack overflow" -e "unexpected monitor-enter" -e "monitor-exit stack underflow" -e "monitor-exit not unlocking" -e "mismatched stack depths"
```


On latest stable I receive the following:
```
08-07 16:52:00.716 10618 10618 I dex2oat32: mismatched stack depths (depth=0, incoming depth=1) in void Gc.onClick(android.view.View)
08-07 16:52:05.438 10618 10618 I dex2oat32: monitor-exit not unlocking the top of the monitor stack while verifying Emg Lmg.c(Tlg)
08-07 16:52:05.438 10618 10618 I dex2oat32: monitor-exit not unlocking the top of the monitor stack while verifying Emg Lmg.c(Tlg)
08-07 16:52:15.644 10618 10638 I dex2oat32: monitor-exit not unlocking the top of the monitor stack while verifying void bi1.i(java.lang.String, hO1)
08-07 16:52:15.647 10618 10638 I dex2oat32: monitor-exit not unlocking the top of the monitor stack while verifying void bi1.i(java.lang.String, hO1)
08-07 16:52:15.758 10618 10640 I dex2oat32: mismatched stack depths (depth=0, incoming depth=1) in exi c0f.r()
08-07 16:52:24.007 10618 10649 I dex2oat32: mismatched stack depths (depth=0, incoming depth=1) in java.lang.Object p8.call()
08-07 16:52:24.009 10618 10649 I dex2oat32: mismatched stack depths (depth=0, incoming depth=1) in java.lang.Object p8.call()
```

I built another APK using Redex master with the following config: 
```
   "passes": [
     "AccessMarkingPass",
     "ReBindRefsPass",
     "InterDexPass",
     "RegAllocPass",
     "MakePublicPass",
     "CopyPropagationPass",
     "DedupBlocksPass",
     "RemoveRecursiveLocksPass"
   ]
```

I put `RemoveRecursiveLocksPass` at the end. I'm not sure if makes more sense before `DedupBlocksPass` instead. Granted I don't think this pass nor the `CopyPropagationPass` changes would resolve the issues with the `Gc` class as the monitor-enter/exit patterns from the original code were pretty straightforward and only the `DedupBlocksPass` is making any substantial changes to code blocks.

With this config I instead receive the following verification errors:
```
08-07 17:12:10.645 11036 11039 I dex2oat32: mismatched stack depths (depth=1, incoming depth=0) in F0k com.snap.payments.lib.api.PaymentsApiHttpInterface$b.m(llk)
08-07 17:12:15.402 11036 11043 I dex2oat32: mismatched stack depths (depth=0, incoming depth=1) in void Gc.onClick(android.view.View)
08-07 17:12:16.901 11036 11045 I dex2oat32: mismatched stack depths (depth=1, incoming depth=0) in Qhd Ekc.d()
08-07 17:12:21.790 11036 11036 I dex2oat32: mismatched stack depths (depth=1, incoming depth=0) in rEa LHa.T()
08-07 17:12:21.830 11036 11048 I dex2oat32: mismatched stack depths (depth=1, incoming depth=0) in t33 LQ2.c(G33)
08-07 17:12:22.507 11036 11036 I dex2oat32: mismatched stack depths (depth=1, incoming depth=0) in hSi NRi.P()
08-07 17:12:22.508 11036 11036 I dex2oat32: mismatched stack depths (depth=1, incoming depth=0) in hSi NRi.P()
08-07 17:12:27.424 11036 11052 I dex2oat32: mismatched stack depths (depth=1, incoming depth=0) in F0k aL3.L()
08-07 17:12:34.165 11036 11059 I dex2oat32: mismatched stack depths (depth=1, incoming depth=0) in java.lang.Object ga9.get()
08-07 17:12:35.897 11036 11036 I dex2oat32: mismatched stack depths (depth=1, incoming depth=0) in q44 iJ3.i(llk, llk)
08-07 17:12:38.118 11036 11036 I dex2oat32: mismatched stack depths (depth=0, incoming depth=1) in java.lang.Object p8.call()
08-07 17:12:38.120 11036 11036 I dex2oat32: mismatched stack depths (depth=0, incoming depth=1) in java.lang.Object p8.call()
08-07 17:12:39.325 11036 11036 I dex2oat32: mismatched stack depths (depth=1, incoming depth=0) in void m6e.a(Tki, java.lang.String, pji, long, long, long, long, lli)
```

I see more monitor issues, but at least they are all now of the same type of failure. My suspicion is `DedupBlocksPass` may not be respecting monitors.

I cherrypicked some of the offending methods in the following [gist](https://gist.github.com/benjaminRomano/863490223678202e5e82d8fd4450deab). Hopefully these are of a more reasonable size. Let me know if there is any more details I can provide.

**Comment by agampe** [comment]
Besides `RemoveRecursiveLocks`, no pass is taking lock information into account right now, AFAIK (`CopyPropagation` historically attempted to leave lock registers alone as a heuristic to not damage things, but it doesn't really understand locking).

That deduping merges equivalent blocks under different locks is strange, though. I'd have expected the original code to be broken, then, as deduping has quite strict requirements on what equivalence means.

Your data is not enough for me to take a look. Since this is not a full `verifier-debug` run, it isn't clear at which join point locks are not the same (also, you should not give smali output, I do not want to have to assemble it to get bytecode offsets), and I do not have the time to do this by hand, when in our case this does not happen (and the "minimal" config is irrelevant - as stated, we do *not* guarantee anything for single passes at the moment, we're a "dirty" compiler where size has been #1 priority mostly).

FYI, our pass order terminates with
```
    DedupBlocksPass,
    ReduceGotosPass,
    MakePublicPass
```
I don't see how `ReduceGotos` would fix anything, though.

You may want to compile with the CFG dumper (`-S 'dump_cfg_classes=[descriptors]', then IRHydra or similar) and see which blocks are merged how, and maybe that gives a hint of what's going wrong where.

Or you may want to "experimentally" extract the lock analysis from `RemoveRecursiveLocks` into a service and then use it in `DedupBlocks`. Quite curious whether it would detect your situation.

**Comment by justinjhendrick** [comment]
> CopyPropagation historically attempted to leave lock registers alone as a heuristic to not damage things, but it doesn't really understand locking

I wrote both `CopyProp` and `DedupBlocks` at about the same time. My incomplete understanding of locking behavior could infect them both :P

**Comment by danzimm** [comment]
Hey!

Today @benjaminRomano and I dug into this issue together and I think we figured out what's going on. As per @agampe 's advice we used the CFG dumper to visualize & confirm our understandings. Before jumping into anything technical [here's](https://gist.github.com/danzimm/6ebbd61969f3f6f715f8c9f685bffb1a) a `cfg` file containing `c0f#r` , a method which exhibits the above issue, so you guys can explore the data too (btw I don't remember this existing back in 2019- awesome infrastructure!)

## The Issue

Ok, so the verifier error above comes from [a part of the method verifier](http://aosp.opersys.com/xref/android-8.0.0_r49/xref/art/runtime/verifier/register_line.cc#428) which ensures that a given instruction[1] always has the same number of monitor calls preceding it, regardless of which blocks preceded it. So, for example if a given block (lets call it `$FOO`) has two predecessors, one contains `MONITOR_ENTER` and the other doesn't then there'll be a verification error when analyzing `$FOO`.

I had a look at DedupBlocks' code and it doesn't explicitly take the "monitor stack" into account when deduping blocks. Usually this would be *ok* as any *correct* code will have a `monitor-exit` instruction, thus eliminating the possibility of deduping code which would have differing monitor stack sizes (i.e. this is due to the fact that blocks that are considered to be merged are initially partitioned by successors).

However, it looks like the base identifies any block which ends on a throw as having [identical successors](https://github.com/facebook/redex/blob/master/service/dedup-blocks/DedupBlocks.cpp#L113) (even though they may have different catch handlers). This is an issue when one throwing block's catch handler contains a `monitor-exit` and the other doesn't. Let me give a more concrete example, you can follow along via [IRHydra](https://mrale.ph/irhydra/1) using [foo.cfg](https://gist.github.com/danzimm/6ebbd61969f3f6f715f8c9f685bffb1a)...

Looking at the bytecode generated after `DedupBlocksPass` we can see that block `B67` looks like the following:
```
const v0, 0
throw v0
```
This block has two direct predecessors: `B66` & `B67`. Digging in we can see the former block doesn't have any indirect predecessors which contain a `monitor-enter`. However, the latter block does in `B7`. We can see that `B7`'s monitor is exited via `B56`, a catch handler which calls `monitor-exit`. We can see, then, that `B67` has imbalanced monitor stack counts when coming from different preceding blocks (and thus is the source of the verifier issue).

Indeed checking out the IR from the end of the `RegAlloc` pass we see that `B67` was originally in two different blocks: `B53` & `B66`.

## The Solution

So what can we do about this? Well it seems there are 2 routes we can go down:
1) Modify `DedupBlocks`'s successor partition function to take into account catch handlers & ensure that the same catch handler will be used
2) Teach `DedupBlocks` about monitor stacks & ensure that blocks will never be dedup'd without having the same preceding monitor stack count

The former feels like a good fix for how DedupBlocks exists right now; that is, we can prove that this fix will solve the verifier issue we're running into. Additionally this will be a pretty simple change to make.

The second fix will correct the issue as we see it now, but also gives us the flexibility of changing DedupBlock's algorithm to be more complex later. For example, we may want to consider deduping portions of blocks that don't have the same successor (i.e. outline common "middle" code). Without taking into account the monitor stack a naive implementation could quickly run into verification issues.

What do you guys think about all this? @benjaminRomano & I will work to get a PR up that addresses these issues, so we'd love to hear any feedback you guys have.

[1]: It seems not every instruction is checked for this property- only ["interesting instructions"](http://aosp.opersys.com/xref/android-8.0.0_r49/xref/art/runtime/verifier/register_line.h#57)

**Comment by agampe** [comment]
Great sleuthing, thanks! I didn't look into `throw` merging in `DedupBlocks`, so didn't think about that problem. I think it was discussed at some point that Redex as-is does not track the connections between throw and handler very well (but neither does the verifier).

I think I'm OK with either as a fix. Nikolai might have an opinion since he worked on deduping and ordering, but he's out for a while.

If you want to do 2, then in a first step move the analysis in `RemoveRecursiveLocks` into a `service/`, and then use it in `DedupBlocks`. The analysis mostly follows the verifier (I think as always there are corner cases...).

> It seems not every instruction is checked for this property- only "interesting instructions"

This should mostly be join points. Traditionally there had been debug modes where it does every instruction, or suspend points, but really the join points are the ones triggering the error here.

**Comment by danzimm** [comment]
> I think I'm OK with either as a fix. Nikolai might have an opinion since he worked on deduping and ordering, but he's out for a while.
Gotcha, I think we'll probably go with (1) for now and look to do (2) once we have a little more breathing room

> If you want to do 2, then in a first step move the analysis in RemoveRecursiveLocks into a service/, and then use it in DedupBlocks. The analysis mostly follows the verifier (I think as always there are corner cases...).
Thanks for the tip! I'll have a look!

> This should mostly be join points. Traditionally there had been debug modes where it does every instruction, or suspend points, but really the join points are the ones triggering the error here.
Ahh this makes sense! Thank you for clarifying!

---

As an aside, I checked out the code that identifies common successors and it looks like it does try to ensure that the same `try` blocks containing the predecessors are the same, so that *should* mean the predecessors have the same catch handlers.

Tomorrow I'll try to dig in and see what's going on here- it seems like a catch handler goes missing somewhere thus making DedupBlock incorrectly dedup these blocks...

**Comment by danzimm** [comment]
Quick follow up (last one of the night): it turns out r8 is outputting the dex file with the catch handler detached... so I guess there's bad bytecode going into redex and redex is just making it worse

**Comment by danzimm** [comment]
Wanted to keep communication flowing: @benjaminRomano & I have a meeting today to discuss this problem and figure out the right path forward.

Here are my thoughts as of right now: I guess we could take route (2) as described above in order to avoid causing further verifier issues when semi-malformed bytecode is present, but at the same time we should figure out why r8 is outputting not-the-best bytecode so we can best leverage redex.

**Comment by benjaminRomano** [comment]
I was able to root cause the issue to [R8 mishandling locks](https://partnerissuetracker.corp.google.com/issues/165825758), which is now patched. Thanks for the tips on debugging the CFG.
