### ISSUE TITLE
Different results between build version and docker version

### ISSUE THREAD

**Issue by geunhayou66** [facebook/redex#568]
Hello.
I've tested redex in two ways for obfuscated apps.
1. Build from source code
2. docker-redex from https://github.com/yongjhih/docker-redex

Used obfuscator is Obfuscapk.
https://github.com/ClaudiuGeorgiu/Obfuscapk

The obfuscator supports various obfuscation techniques.
To test redex' optimization performance, I used obfuscation techniques in code category of Obfuscapk.
The techniques in code category include 'Arithmetic branch', 'Goto', 'Nop', 'Method overload', 'Call indirection'.

When I used builded version from source code, it showed excellent optimization performance in removing 'Goto', 'Nop' and 'Arithmetic branch' of obfuscated apps.
But it cannot affect call indirection.

However, when I used docker version, it can remove most of methods generated by 'Call indirection'.
On the contrary, the docker version cannot remove 'Goto', 'Nop' and 'Arithmetic branch' of obfuscated apps.

Why the two versions of redex show different results?

I attached sample apps.
One is original version, another is obfuscated version, another is optimized version by builded-redex, and the other is optimized version by docker-redex.

Can you explain me?
[sample.zip](https://github.com/facebook/redex/files/5588303/sample.zip)

**Comment by amnn** [comment]
Hi @geunhayou66, 

We do not own [yongjhih/docker-redex](https://github.com/yongjhih/docker-redex), it appears to be a fork from five years ago.  Since then, we have invested in Redex's optimizations, so building from source from a recent checkout of this repository will give you the set of optimizations we are currently working with.  As a result, I would not expect the two ways of building and running Redex you described to produce the same results (I would be kind of worried if they did!)

I am not entirely sure which class of optimizations you mean by "Call indirection", but Redex is able to inline methods, devirtualize them or collapse class hierarchies when necessary, but it may choose not to based on heuristics.  These are not always optimal and Redex is designed to reduce size so its heuristics are tuned with that goal in mind.  Optimizations like inlining can increase a method's contribution to the APK (by duplicating it across its call sites), so this may be another reason why Redex is choosing not to do that.

Finally, it could be that if you ran more passes over the APK, more of the examples you were expecting to be optimized would go away.  By default Redex runs with [this configuration](https://github.com/facebook/redex/blob/master/config/default.config), but also comes with a [more aggressive configuration](https://github.com/facebook/redex/blob/master/config/aggressive.config).  Try comparing the results from explicitly passing these configs to Redex (Using the `--config` parameter to the python wrapper script), to see if the more aggressive variant helps.

I'm closing this issue because the original question of the difference between the two versions is answered.  If you believe there is an issue with the optimizations the current version of Redex is applying, feel free to open a new issue.

P.S. If you are interested in building and running the latest Redex source within a Docker image, we now have a script to do that: [`container/run`](https://github.com/facebook/redex/blob/master/container/run), which will create and start a docker image with all the necessary dependencies, and the Redex repo mounted there.

**Comment by geunhayou66** [comment]
Thanks to you reply!
