### ISSUE TITLE
open trace file setting

### ISSUE THREAD

**Issue by PerceiverDo** [facebook/redex#584]
how to setting the trace, so that i can check this process.
`

> Trace settings:
> TRACEFILE=
> SHOW_TIMESTAMPS=
> SHOW_TRACEMODULE=
> TRACE_METHOD_FILTER=

`

**Comment by agampe** [comment]
Tracing is configured with the `TRACE` environment variable.

For example, `TRACE=PM:1,TIME:1` is the default [inserted by `redex.py`](https://github.com/facebook/redex/blob/9c5a55219f70646aeab09516f5f652242e3f9218/redex.py#L462) if nothing else is set and will give the listing of [which passes the `PassManager` is running](https://github.com/facebook/redex/blob/9c5a55219f70646aeab09516f5f652242e3f9218/libredex/PassManager.cpp#L941) and [how long `Timer` scopes take](https://github.com/facebook/redex/blob/9c5a55219f70646aeab09516f5f652242e3f9218/libredex/Timer.cpp#L25). The category exactly matches the values in [`libredex/Trace.h`](https://github.com/facebook/redex/blob/9c5a55219f70646aeab09516f5f652242e3f9218/libredex/Trace.h#L20). The higher the number the more verbose the output. For a line
```cpp
  TRACE(X, Y, "Some text");
```
in the code to be printed, category X needs to be at least Y in `TRACE`.

`TRACEFILE=/path/to/logfile` will redirect the trace output to a file. Otherwise it goes to stderr.
