### ISSUE TITLE
Couldn't find zipalign.  Your APK may not be fully optimized.

### ISSUE THREAD

**Issue by arifnadeem7** [facebook/redex#60]
This is being shown for an apk which I have aligned using zipalign tool.

**Comment by Huang-Liangjin** [comment]
I got the same problem.
And here is a solution I tried it but nothing helps.
https://github.com/facebook/redex/issues/51

**Comment by matejvida** [comment]
I pulled the new code for redex and folly, installed it but it still does not work.

I get this:

After update this line does not appear -> (Optimization warning: Pure abstract class passed to encode: 1 occurrences)
Couldn't find zipalign. Your APK may not be fully optimized.

When using this cmd:

redex ./APK/app-dev-debug.apk -o ./APK/output.apk

Is this a bug ore something, because i have zipalign located /Users/hq/Library/Android/sdk/build-tools/23.0.2

Also this folder can change when android build tools update.

Any suggestions?

**Comment by fujinjun** [comment]
sample problem,tried the fixes but nothing help.

**Comment by fujinjun** [comment]
i have resolved by set ANDROID_SDK environment to android sdk home folder(which is used at redex.py line 54)

**Comment by arifnadeem7** [comment]
@fujinjun I can confirm that setting ANDROID_SDK doesn't help me in any way.

**Comment by jaredrummler** [comment]
You need to add build-tools to your `PATH` (see #28)

**Comment by bertmaher** [comment]
I've added this to the FAQ in the README, thanks for reporting it.  (and to @jaredrummler for the solution).
