### ISSUE TITLE
When I run 'autoreconf -ivf && ./configure && make -j', computer memory is exhausted...

### ISSUE THREAD

**Issue by fujian26** [facebook/redex#628]
When I run 'autoreconf -ivf && ./configure && make -j', computer memory is exhausted, and it can't continue to compile.

MacOs Big Sur.

**Comment by agampe** [comment]
`make -j` lets Make auto-scale dependent on load. If you do not have something akin to 4GB per core, it is not a good idea.

I will update the documentation to give memory-constrained defaults instead of optimizing for a high-end system, even though it is mentioned there already. See [here](https://fbredex.com/docs/installation#download-build-and-install): "If you experience out-of-memory errors, reduce Make parallelism, e.g., to `-j4`."

**Comment by agampe** [comment]
Updated in b74cb45b.
