### ISSUE TITLE
Build ReDex using autoconf and make fails

### ISSUE THREAD

**Issue by jingweih-doordash** [facebook/redex#644]
redex % autoreconf -ivf && ./configure && make
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
configure.ac:18: error: AM_INIT_AUTOMAKE expanded multiple times
/usr/local/Cellar/automake/1.16.5/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:6: the top level
/usr/local/Cellar/automake/1.16.5/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:18: the top level
autom4te: error: /usr/local/opt/m4/bin/m4 failed with exit status: 1
aclocal: error: /usr/local/Cellar/autoconf/2.71/bin/autom4te failed with exit status: 1
autoreconf: error: aclocal failed with exit status: 1

**Comment by Kewen12** [comment]
> same issue not sure how to fix it

Hi! Was the issue for the latest commit? Would you please provide more information about the OS/autoconf version so I can try to reproduce it? Thanks.

**Comment by khiawyen** [comment]
@Kewen12 It looks like the issue comes from automake 1.16.5. I can build after downgrading automake version to 1.16.3.

@jingweih-doordash @rayanke 
To downgrade,
`cd
wget https://ftp.gnu.org/gnu/automake/automake-1.16.3.tar.gz
tar xf automake-1.16.3.tar.gz
cd automake-1.16.3
./configure --prefix=/usr/local
make
sudo make install`

**Comment by Kewen12** [comment]
@khiawyen Thanks for the feedback. Fix on the way.
