### ISSUE TITLE
Understanding the --stop-pass and --output-ir flags

### ISSUE THREAD

**Issue by xinyuliu12** [facebook/redex#645]
Hello guys,

I am new to the redex and plan to understand the effect of each pass by running them on simple dex files.
Based on my understanding about the help messages, `--stop-pass` and `--output-ir` seem helpful options that can provide me with an opportunity to digest the resulting IR code. So I successfully run the redex using the following command:
`
./redex-all -o ../data/ --dex-files ../data/BuiltInFunctions.dex --stop-pass 4 --output-ir ../data/
`
The resulting `../data` directory has a file named `irmeta.bin`, which I assume stores the ir code after running the pass number 4.
My question is: how can I open and read this file? Also, can you please give me some advice on getting familiar with the redex IR? Is it similar to the LLVM IR?

Thanks for your help!

**Comment by Feng23** [comment]
Hi, the usage is experimental, `redex-all` outputs dex files instead of IR with the two options. You can find `*.dex` in the output directory. You may compare the input dexes and output dexes to understand the pass effect. The `irmeta.bin` contains some meta data like deobfuscated names and reference stats, which is used to recover the redex program state so that another tool `redex-opt` could take the dexes and metadata as input and run passes on the input.

These are all experimental features. Let me know if you have further questions.
