### ISSUE TITLE
configure: error: Please install jsoncpp

### ISSUE THREAD

**Issue by 1994jeff** [facebook/redex#694]
please help
I get this error when compile redex use command “autoreconf -ivf && ./configure --with-boost=$BOOST_ROOT --enable-protobuf”

`
configure: error: Please install jsoncpp
`

I use macos big sur， m1，system version 11.6，
and aleady install jsoncpp 1.9.5。
when I run commad “brew install jsoncpp”
Warning: jsoncpp 1.9.5 is already installed and up-to-date.
To reinstall 1.9.5, run:
  brew reinstall jsoncpp

**Comment by yuxuanchen1997** [comment]
I am guessing what's happening is that the system compiler is not aware of homebrew's LIBRARY_PATH. Homebrew for M1 by default installs libraries in /opt/homebrew/ instead of /usr/local. 

Can you try this? https://apple.stackexchange.com/questions/414622/installing-a-c-c-library-with-homebrew-on-m1-macs

**Comment by 1994jeff** [comment]
> I am guessing what's happening is that the system compiler is not aware of homebrew's LIBRARY_PATH. Homebrew for M1 by default installs libraries in /opt/homebrew/ instead of /usr/local.
> 
> Can you try this? https://apple.stackexchange.com/questions/414622/installing-a-c-c-library-with-homebrew-on-m1-macs

thanks, It works for me
